"""
Python bindings for the trading engine
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['BUY', 'FOK', 'GTC', 'IOC', 'LIMIT', 'MARKET', 'MarketSnapshot', 'OrderType', 'PortfolioSnapshot', 'RawOrderParams', 'SELL', 'STOP_LIMIT', 'STOP_MARKET', 'Side', 'SystemMetrics', 'TimeInForce', 'TradeExecutedEvent', 'TradingSystem']
class MarketSnapshot:
    def __init__(self) -> None:
        ...
    @property
    def best_ask(self) -> int:
        ...
    @property
    def best_ask_quantity(self) -> int:
        ...
    @property
    def best_bid(self) -> int:
        ...
    @property
    def best_bid_quantity(self) -> int:
        ...
    @property
    def last_trade_price(self) -> int:
        ...
    @property
    def last_trade_quantity(self) -> int:
        ...
    @property
    def recent_trades(self) -> list[int]:
        ...
class OrderType:
    """
    Members:
    
      LIMIT
    
      MARKET
    
      STOP_MARKET
    
      STOP_LIMIT
    """
    LIMIT: typing.ClassVar[OrderType]  # value = <OrderType.LIMIT: 0>
    MARKET: typing.ClassVar[OrderType]  # value = <OrderType.MARKET: 1>
    STOP_LIMIT: typing.ClassVar[OrderType]  # value = <OrderType.STOP_LIMIT: 3>
    STOP_MARKET: typing.ClassVar[OrderType]  # value = <OrderType.STOP_MARKET: 2>
    __members__: typing.ClassVar[dict[str, OrderType]]  # value = {'LIMIT': <OrderType.LIMIT: 0>, 'MARKET': <OrderType.MARKET: 1>, 'STOP_MARKET': <OrderType.STOP_MARKET: 2>, 'STOP_LIMIT': <OrderType.STOP_LIMIT: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class PortfolioSnapshot:
    def __init__(self) -> None:
        ...
    @property
    def balance(self) -> int:
        ...
    @property
    def positions(self) -> dict[int, int]:
        ...
    @property
    def trade_history(self) -> list[TradeExecutedEvent]:
        ...
class RawOrderParams:
    order_type: OrderType
    price: str
    side: Side
    stop_price: str
    symbol: str
    time_in_force: TimeInForce
    def __init__(self) -> None:
        ...
    @property
    def quantity(self) -> int:
        ...
    @quantity.setter
    def quantity(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def trader_id(self) -> int:
        ...
    @trader_id.setter
    def trader_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class Side:
    """
    Members:
    
      BUY
    
      SELL
    """
    BUY: typing.ClassVar[Side]  # value = <Side.BUY: 0>
    SELL: typing.ClassVar[Side]  # value = <Side.SELL: 1>
    __members__: typing.ClassVar[dict[str, Side]]  # value = {'BUY': <Side.BUY: 0>, 'SELL': <Side.SELL: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SystemMetrics:
    def __init__(self) -> None:
        ...
    @property
    def active_orders(self) -> int:
        ...
    @property
    def avg_latency_ms(self) -> float:
        ...
    @property
    def event_queue_depth(self) -> int:
        ...
    @property
    def orders_processed(self) -> int:
        ...
    @property
    def throughput(self) -> float:
        ...
class TimeInForce:
    """
    Members:
    
      GTC
    
      IOC
    
      FOK
    """
    FOK: typing.ClassVar[TimeInForce]  # value = <TimeInForce.FOK: 2>
    GTC: typing.ClassVar[TimeInForce]  # value = <TimeInForce.GTC: 0>
    IOC: typing.ClassVar[TimeInForce]  # value = <TimeInForce.IOC: 1>
    __members__: typing.ClassVar[dict[str, TimeInForce]]  # value = {'GTC': <TimeInForce.GTC: 0>, 'IOC': <TimeInForce.IOC: 1>, 'FOK': <TimeInForce.FOK: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TradeExecutedEvent:
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex, arg4: typing.SupportsInt | typing.SupportsIndex, arg5: Side, arg6: typing.SupportsInt | typing.SupportsIndex, arg7: typing.SupportsInt | typing.SupportsIndex, arg8: typing.SupportsInt | typing.SupportsIndex, arg9: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def aggressing_order_id(self) -> int:
        ...
    @property
    def aggressing_order_remaining_quantity(self) -> int:
        ...
    @property
    def aggressing_side(self) -> Side:
        ...
    @property
    def aggressing_trader_id(self) -> int:
        ...
    @property
    def price(self) -> int:
        ...
    @property
    def quantity(self) -> int:
        ...
    @property
    def resting_order_id(self) -> int:
        ...
    @property
    def resting_order_remaining_quantity(self) -> int:
        ...
    @property
    def resting_trader_id(self) -> int:
        ...
    @property
    def symbol_id(self) -> int:
        ...
class TradingSystem:
    def __init__(self, tick_interval_ms: typing.SupportsInt | typing.SupportsIndex, symbols: collections.abc.Sequence[str]) -> None:
        ...
    def add_market_maker_trader(self, arg0: str, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsFloat | typing.SupportsIndex, arg3: typing.SupportsFloat | typing.SupportsIndex, arg4: typing.SupportsInt | typing.SupportsIndex, arg5: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> bool:
        ...
    def add_random_limit_trader(self, arg0: str, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def add_random_market_trader(self, arg0: str, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def are_automated_traders_enabled(self) -> bool:
        ...
    def cancel_order(self, order_id: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def create_portfolio(self, starting_balance: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def enable_automated_traders(self, arg0: bool) -> None:
        ...
    def get_all_symbols(self) -> list[str]:
        ...
    def get_market_snapshot(self, symbol: str) -> trading_engine_py.MarketSnapshot | None:
        ...
    def get_portfolio_snapshot(self, trader_id: typing.SupportsInt | typing.SupportsIndex) -> trading_engine_py.PortfolioSnapshot | None:
        ...
    def get_system_metrics(self) -> SystemMetrics:
        ...
    def get_tick_interval(self) -> int:
        ...
    def get_trader_parameters(self, arg0: str) -> dict[str, float] | None:
        ...
    def is_running(self) -> bool:
        ...
    def remove_trader(self, arg0: str) -> bool:
        ...
    def set_tick_interval(self, tick_length_ms: typing.SupportsInt | typing.SupportsIndex) -> bool:
        ...
    def set_trader_parameters(self, arg0: str, arg1: collections.abc.Mapping[str, typing.SupportsFloat | typing.SupportsIndex]) -> bool:
        ...
    def start(self) -> None:
        ...
    def stop(self) -> None:
        ...
    def submit_order(self, trader_id: typing.SupportsInt | typing.SupportsIndex, params: RawOrderParams) -> int:
        ...
BUY: Side  # value = <Side.BUY: 0>
FOK: TimeInForce  # value = <TimeInForce.FOK: 2>
GTC: TimeInForce  # value = <TimeInForce.GTC: 0>
IOC: TimeInForce  # value = <TimeInForce.IOC: 1>
LIMIT: OrderType  # value = <OrderType.LIMIT: 0>
MARKET: OrderType  # value = <OrderType.MARKET: 1>
SELL: Side  # value = <Side.SELL: 1>
STOP_LIMIT: OrderType  # value = <OrderType.STOP_LIMIT: 3>
STOP_MARKET: OrderType  # value = <OrderType.STOP_MARKET: 2>
